### ISSUE TITLE
how to use on linux vm/chrome os

### ISSUE THREAD

**Issue by EndingGeckoez69** [CoC-Fire/ytviewbot#2]
Your .zip won't work with Chrome OS because it's an incompatible file type, even using the linux vm. Please try to make this compatible with Chrome OS. Thx

**Comment by eepyfemboi** [comment]
It currently only works for windows anyway, so if you want to try fixing it for linux, go ahead. The problem is the file path for chromedriver. All you have to do is switch out C;/Perflogs/chromedriver.exe for whatever works. I'm not gonna invest too much time in it at this point, because I don't even have a working linux pc at the moment, so I'm either gonna have to set up a vm or fix it, which I also don't have time for. Good luck!
